routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\LoginController;
use App\Http\Controllers\Backend\DepartController;
use App\Http\Controllers\Backend\MarriesController;
use App\Http\Controllers\Backend\VillageController;
use App\Http\Livewire\Backend\Divid\DividComponent;
use App\Http\Livewire\Backend\Order\OrderComponent;
use App\Http\Livewire\Backend\Order\PrintBillOrder;
use App\Http\Controllers\Backend\DistrictController;
use App\Http\Controllers\Backend\EmployeeController;
use App\Http\Controllers\Backend\PositionController;
//use App\Http\Controllers\Backend\Account\BranchController;
use App\Http\Controllers\Backend\ProvinceController;
use App\Http\Livewire\Backend\Order\DoSendComponent;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Livewire\Backend\Divid\AddDividComponent;
use App\Http\Livewire\Backend\Order\DoneSendComponent;
use App\Http\Livewire\Backend\Coupons\CouponsComponent;
use App\Http\Livewire\Backend\Divid\EditDividComponent;
use App\Http\Livewire\Backend\Employee\EmployeeContent;
use App\Http\Livewire\Backend\Order\EditOrderComponent;
use App\Http\Livewire\Backend\Order\OrderItemComponent;
use App\Http\Livewire\Backend\Customer\CustomerComponent;
use App\Http\Livewire\Backend\Order\CancelOrderComponent;
use App\Http\Controllers\Backend\Payroll\SalaryController;
use App\Http\Livewire\Backend\Coupons\AddCouponsComponent;
use App\Http\Livewire\Backend\Order\ConfirmOrderComponent;
//livewire
//by cheeyeeyang mouasue
use App\Http\Livewire\Backend\Order\SendingOrderComponent;
use App\Http\Controllers\Backend\Doc\StorageFileController;
use App\Http\Controllers\Backend\Ecommerce\SlideController;
use App\Http\Controllers\Backend\Payroll\PayrollController;
use App\Http\Livewire\Backend\Coupons\EditCouponsComponent;
use App\Http\Livewire\Backend\Order\DetailPaymentComponent;
use App\Http\Livewire\Backend\Order\EditOrderItemComponent;
use App\Http\Livewire\Backend\Payroll\PayrollBeforeContent;
use App\Http\Controllers\Backend\Account\CurrencyController;
use App\Http\Controllers\Backend\Doc\DocumentTypeController;
use App\Http\Controllers\Backend\Account\StatusAccController;
use App\Http\Controllers\Backend\Doc\ExternalPartsController;
use App\Http\Controllers\Backend\Doc\LocalDocumentController;
use App\Http\Controllers\Backend\Ecommerce\CatalogController;
use App\Http\Controllers\Backend\Ecommerce\ProductController;
use App\Http\Controllers\Backend\Ecommerce\ServiceController;
use App\Http\Livewire\Backend\Order\ShowCancelOrderComponent;
use App\Http\Controllers\Backend\Account\SettingAccController;
use App\Http\Controllers\Backend\Doc\ExportDocumentController;
use App\Http\Controllers\Backend\Doc\ImportDocumentController;
use App\Http\Controllers\Backend\Account\TransectionController;
use App\Http\Livewire\Backend\Order\UpdateOrderCancelComponent;

//end
/*
Route::get('/', function () {
return view('backend.login');
});*/

//App::setLocale($locale);
//Route::get('localization/{local}',[LocalController::class, 'index']);
Route::get('localization/{local}', function ($local) {
    Session::put('local', $local);
    return back();
});

//Frontend Website
Route::get('/', App\Http\Livewire\Frontend\HomeComponent::class)->name('home');
Route::get('/shop', App\Http\Livewire\Frontend\ShopComponent::class)->name('shop');
Route::get('/shop/product_detail/{id}', App\Http\Livewire\Frontend\ProductDetailComponent::class)->name('product_detail');
Route::get('/services', App\Http\Livewire\Frontend\ServiceComponent::class)->name('services');
Route::get('/services/service_detail/{id}', App\Http\Livewire\Frontend\ServiceDetailComponent::class)->name('service_detail');
Route::get('/customers', App\Http\Livewire\Frontend\CustomersComponent::class)->name('customers');
Route::get('/frontend/solutions', App\Http\Livewire\Frontend\SolutionsComponent::class)->name('solutions');
Route::get('/frontend/solutions/solution_detail/{id}', App\Http\Livewire\Frontend\SolutionsDetailComponent::class)->name('solution_detail');
Route::get('/about', App\Http\Livewire\Frontend\AboutComponent::class)->name('about');
Route::get('/contact', App\Http\Livewire\Frontend\ContactComponent::class)->name('contact');
Route::get('/cart', App\Http\Livewire\Frontend\CartComponent::class)->name('cart');
// Route::get('/checkout', App\Http\Livewire\Frontend\CheckoutComponent::class)->name('checkout');
Route::get('/wishlist', App\Http\Livewire\Frontend\WishlistComponent::class)->name('wishlist');
Route::get('/terms', App\Http\Livewire\Frontend\TermsComponent::class)->name('terms');
Route::get('/frontend/news', App\Http\Livewire\Frontend\NewsComponent::class)->name('news');
Route::get('/frontend/news/news_detail/{id}', App\Http\Livewire\Frontend\NewsDetailComponent::class)->name('news_detail');
//thankyou
Route::get('/thank-you', App\Http\Livewire\Frontend\ThankyouComponent::class)->name('thankyou');
Route::get('/privacy', function () {
    return file_get_contents(public_path() . '/privacy.html');
});

//Customers CustomerLoginComponent
Route::get('/customers/sign_in', App\Http\Livewire\Frontend\Auth\CustomerLoginComponent::class)->name('customer_sign_in');
Route::get('/customers/register', App\Http\Livewire\Frontend\Auth\CustomerRegisterComponent::class)->name('customer_register');

Route::resource('/loginadmincit', LoginController::class);

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
Route::post('/saveToken', [LoginController::class, 'saveToken']);

// ============================  for admin ================= //
Route::group(['middleware' => 'adminLogin'], function () {
    //Customer
    Route::get('/customers/dashboard', App\Http\Livewire\Frontend\Customer\DashboardComponent::class)->name('customer.dashboard');
    Route::get('/customers/profile/{id}', App\Http\Livewire\Frontend\Auth\CustomerProfileComponent::class)->name('customer.profile');
    Route::get('/customers/shipping/{id}', App\Http\Livewire\Frontend\Auth\CustomerShippingComponent::class)->name('customer.shipping');
    Route::get('/customers/sign_out', [App\Http\Livewire\Frontend\Auth\CustomerLoginComponent::class, 'signOut'])->name('customer_sign_out');
    Route::get('/history', App\Http\Livewire\Frontend\Customer\CustomerHistoryComponent::class)->name('customer.history');
    Route::get('/view-history/{order_slug}/orderdetail', App\Http\Livewire\Frontend\Customer\ShowCustomerHistoryComponent::class)->name('customer.showhistory');
    Route::get('/order-divid', App\Http\Livewire\Frontend\Customer\OrderDivid::class)->name('customer.orderdivid');
    Route::get('/withraw-divid', App\Http\Livewire\Frontend\Customer\WithrawDividComponent::class)->name('customer.withrawdivid');
    Route::get('/withraw-success', App\Http\Livewire\Frontend\Customer\WithrawSuccessComponent::class)->name('customer.withdrawsuccess');
    Route::get('/liked-product', App\Http\Livewire\Frontend\Customer\LikedProductComponent::class)->name('customer.likedproduct');
    Route::get('/daily-customer-order-cart', App\Http\Livewire\Frontend\Customer\DailyCustomerCartComponent::class)->name('customer.dailycart');
    Route::get('/history-withraw-balance', App\Http\Livewire\Frontend\Customer\HistoryWithrawaComponent::class)->name('customer.historywithraw');
    Route::get('/daily-customer-shop', App\Http\Livewire\Frontend\Customer\DailyCustomerShopComponent::class)->name('customer.dailycustomershop');
    Route::get('/checkout', App\Http\Livewire\Frontend\CheckoutComponent::class)->name('checkout');
    //Backend
    Route::get('/module', [App\Http\Controllers\Backend\ModuleController::class, 'index'])->name('module.index');
    Route::resource('/dashboard', DashboardController::class);
    Route::resource('/depart', DepartController::class);
    Route::resource('/province', ProvinceController::class);
    Route::resource('/district', DistrictController::class);
    Route::resource('/village', VillageController::class);
    Route::resource('/marries', MarriesController::class);
    Route::resource('/position', PositionController::class);
    Route::resource('/user', UserController::class);

    Route::post('/user-excel', [App\Http\Controllers\Backend\ExcelUserController::class, 'store']);
    Route::get('/user-excel', [App\Http\Controllers\Backend\ExcelUserController::class, 'index']);
    Route::get('/user/changepass/{id}', [UserController::class, 'changepass'])->name('user.changepass');
    Route::PATCH('/user/updatepass/{id}', [UserController::class, 'updatepass'])->name('user.updatepass');
    Route::resource('/role', RoleController::class);
    Route::resource('/branch', App\Http\Controllers\Backend\BranchController::class);
    Route::resource('/misstype', App\Http\Controllers\Backend\MissTypeController::class);

    Route::resource('/transection', TransectionController::class);
    Route::PATCH('/approved/{id}', [TransectionController::class, 'approved'])->name('transection.approved');
    Route::PATCH('/rejected/{id}', [TransectionController::class, 'rejected'])->name('transection.rejected');
    //Route::resource('/branch',BranchController::class);
    Route::resource('/statusacc', StatusAccController::class);
    Route::resource('/currency', CurrencyController::class);
    Route::resource('/settingacc', SettingAccController::class);

    Route::resource('/import_doc', ImportDocumentController::class);
    Route::get('/import_doc/download/{id}', [ImportDocumentController::class, 'download'])->name('download_import');
    Route::resource('/export_doc', ExportDocumentController::class);
    Route::get('/export_doc/download/{id}', [ExportDocumentController::class, 'download'])->name('download_export');
    Route::resource('/local_doc', LocalDocumentController::class);

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Employee;
use App\Models\Role;
use App\Models\Branch;
use App\Models\Divid;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::orderBy('id','desc')->get();
        return view('backend.settings.user.index', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $emp = Employee::where('del',0)->get();
        $role = Role::where('del',0)->get();
        $branch = Branch::all();
        $divid=Divid::all();
        return view('backend.settings.user.create', compact('emp','role','branch','divid'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'phone'=>'required|unique:users,phone|min:8',
            //'email'=>'required|email',
            'password'=>'required|min:6',
            'confirmpassword'=>'required|same:password',
            //'emp_id'=>'required',
            'role_id'=>'required'
        ],[
            'name.required'=>'ກະລຸນາໃສ່ຊື່ຜູ້ໃຊ່ກ່ອນ!',
            'phone.required'=>'ກະລຸນາໃສ່ເບີໂທລະສັບກ່ອນ!',
            'phone.unique'=>'ເບີໂທນີ້ ໄດ້ມີໃນລະບົບແລ້ວ!',
            'phone.min'=>'ເບີໂທຕ້ອງແມ່ນ 8 ຕົວເລກ! ຕົວຢ່າງ: XXXXXXXX',
            //'email.required'=>'ກະລຸນາໃສ່ Email ກ່ອນ!',
            //'email.email'=>'ຮູບແບບ Email ບໍ່ຖືກຕ້ອງ!',
            'password.required'=>'ໃສ່ລະຫັດຜ່ານກ່ອນ!',
            'password.min'=>'ລະຫັດຜ່ານຕ້ອງແມ່ນ 6 ຕົວເລກຂື້ນໄປ!',
            'confirmpassword.required'=>'ກະລຸນາຢືນຢັນລະຫັດຜ່ານຄືນກ່ອນ!',
            'confirmpassword.same'=>'ຢືນຢືນລະຫັດຜ່ານ ບໍ່ຄືກັນກັບ ຫ້ອງລະຫັດຜ່ານຂ້າງເທິງ',
            //'emp_id.required'=>'ກະລຸນາເລືອກພະນັກງານກ່ອນ!',
            'role_id.required'=>'ກະລຸນາເລືອກສິດນຳໃຊ້ກ່ອນ!'
        ]);
        User::create([
            'name'=> $request->name,
            'phone'=> $request->phone,
            'email'=>$request->email,
            'password'=>bcrypt($request->password),
            'emp_id'=>$request->emp_id,
            'branch_id'=>$request->branch_id,
            'role_id'=>$request->role_id,
            'divid_id'=>$request->divid_id
        ]);
        return redirect()->route('user.index')->with('success','ເພີ່ມຂໍ້ມູນສຳເລັດ!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $emp = Employee::where('del',0)->get();
        $role = Role::where('del',0)->get();
        $branch = Branch::all();
        $divid=Divid::all();
        return view('backend.settings.user.edit', compact('emp','role','user','branch','divid'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $request->validate([
            'name' => 'required',
            'phone'=>'required|min:8',
            //'email'=>'required|email',
            //'emp_id'=>'required',
            'role_id'=>'required'
        ],[
            'name.required'=>'ກະລຸນາໃສ່ຊື່ຜູ້ໃຊ່ກ່ອນ!',
            'phone.required'=>'ກະລຸນາໃສ່ເບີໂທລະສັບກ່ອນ!',
            'phone.min'=>'ເບີໂທຕ້ອງແມ່ນ 8 ຕົວເລກ! ຕົວຢ່າງ: XXXXXXXX',
            //'email.required'=>'ກະລຸນາໃສ່ Email ກ່ອນ!',
            //'email.email'=>'ຮູບແບບ Email ບໍ່ຖືກຕ້ອງ!',
            'confirmpassword.required'=>'ກະລຸນາຢືນຢັນລະຫັດຜ່ານຄືນກ່ອນ!',
            'confirmpassword.same'=>'ຢືນຢືນລະຫັດຜ່ານ ບໍ່ຄືກັນກັບ ຫ້ອງລະຫັດຜ່ານຂ້າງເທິງ',
            //'emp_id.required'=>'ກະລຸນາເລືອກພະນັກງານກ່ອນ!',
            'role_id.required'=>'ກະລຸນາເລືອກສິດນຳໃຊ້ກ່ອນ!'
        ]);
        if($request->input('password'))
        {
            $user_date = [
                'name'=> $request->name,
                'phone'=> $request->phone,
                'email'=>$request->email,
                'password'=>bcrypt($request->password),
                'emp_id'=>$request->emp_id,
                'branch_id'=>$request->branch_id,
                'role_id'=>$request->role_id,
            ];
        }
        else
        {
            $user_date = [
                'name'=> $request->name,
                'phone'=> $request->phone,
                'email'=>$request->email,
                'emp_id'=>$request->emp_id,
                'branch_id'=>$request->branch_id,
                'role_id'=>$request->role_id,
            ];
        }
        $user->update($user_date);
        if($request->divid_id){
            $user->divid_id=$request->divid_id;
            $user->save();
        }
        return redirect()->route('user.index')->with('success','ແກ້ໄຂຂໍ້ມູນສຳເລັດ!');
    }

    public function changepass($id)
    {
        $user = User::find($id);
        return view('backend.settings.user.changepass', compact('user'));
    }
    public function updatepass(Request $request, $id)
    {
        $user = User::find($id);
        $request->validate([
            'name' => 'required',
            'phone'=>'required|min:8',
        ],[
            'name.required'=>'ກະລຸນາໃສ່ຊື່ຜູ້ໃຊ່ກ່ອນ!',
            'phone.required'=>'ກະລຸນາໃສ່ເບີໂທລະສັບກ່ອນ!',
            'phone.min'=>'ເບີໂທຕ້ອງແມ່ນ 8 ຕົວເລກ! ຕົວຢ່າງ: XXXXXXXX',
            'confirmpassword.required'=>'ກະລຸນາຢືນຢັນລະຫັດຜ່ານຄືນກ່ອນ!',
            'confirmpassword.same'=>'ຢືນຢືນລະຫັດຜ່ານ ບໍ່ຄືກັນກັບ ຫ້ອງລະຫັດຜ່ານຂ້າງເທິງ',
        ]);
        if($request->input('password'))
        {
            $user_date = [
                'name'=> $request->name,
                'phone'=> $request->phone,
                'email'=>$request->email,
                'password'=>bcrypt($request->password),
            ];
        }
        else
        {
            $user_date = [
                'name'=> $request->name,
                'phone'=> $request->phone,
                'email'=>$request->email,
            ];
        }
        $user->update($user_date);
        return redirect()->back()->with('success','ແກ້ໄຂຂໍ້ມູນສຳເລັດ!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect()->back()->with('success','ລຶບຂໍ້ມູນສຳເລັດ!');
    }
   
}

resources/views/backend/settings/user/create.blade.php
@extends('layouts.app.app')
@section('content')
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>{{__('lang.user')}}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('dashboard.index')}}">{{__('lang.home')}}</a></li>
            <li class="breadcrumb-item active">{{__('lang.user')}}</li>
          </ol>
        </div>
      </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="col-lg-12">
          <div class="card card-default">

            <div class="card-header">
              <h3 class="card-title"><h4 class="card-title">{{__('lang.add')}}</h4></h3>
  
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>

            @if(count($errors)>0)
              <div class="card-body">
                <div class="alert alert-danger alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <i class="icon fas fa-ban"> {{__('lang.error')}}</i></br>
                  @foreach($errors->all() as $error)
                  {{$error}} </br>
                  @endforeach
                </div>
              </div>
            @endif 
            
            
            <form method="POST" action="{{route('user.store')}}">
                @csrf
                <div class="card-body">
                  
                  <div class="row">
                    <div class="col-md-6">

                      <div class="row">
                        <div class="col-md-12">
                          <div class="form-group">
                            <label for="username">{{__('lang.username')}}</label>
                            <input type="text" class="form-control" name="name" placeholder="{{__('lang.username')}}">
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group">
                            <label for="phone">{{__('lang.phone')}}</label>
                            <input type="text" class="form-control" name="phone" placeholder="{{__('lang.phone')}}">
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group">
                            <label for="email">{{__('lang.email')}}</label>
                            <input type="email" class="form-control" name="email" placeholder="{{__('lang.email')}}">
                          </div>
                        </div>
                      </div>

                      <div class="row">
                        <div class="col-md-12">
                        <div class="form-group">
                          <label>{{__('lang.divid_name')}}</label>
                          <select class="form-control select2" name="divid_id" style="width: 100%;">
                                <option value="" selected>{{__('lang.select')}}</option>          
                            @foreach($divid as $item)
                                <option value="{{$item->id}}"> {{$item->name}} - {{$item->percent}} %</option>
                            @endforeach
                          </select>
                        </div>
                        </div>
                      </div>

                      <div class="row">
                          <div class="col-md-12">
                            <div class="form-group">
                              <label for="password">{{__('lang.password')}}</label>
                              <input type="password" class="form-control" name="password" placeholder="{{__('lang.password')}}">
                            </div>
                          </div>
                          <div class="col-md-12">
                            <div class="form-group">
                              <label for="confirmpassword">{{__('lang.confirmpassword')}}</label>
                              <input type="password" class="form-control" name="confirmpassword" placeholder="{{__('lang.confirmpassword')}}">
                            </div>
                          </div>
                      </div>
                    </div>
                    <!-- /.col -->
                    
                    <div class="col-md-6">

                      <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                              <label>{{__('lang.employee')}}</label>
                              <select class="form-control select2" name="emp_id" style="width: 100%;">
                                <option value="" selected>{{__('lang.select')}}</option>                      
                                @foreach($emp as $e)
                                    <option value="{{$e->id}}">{{$e->firstname}} {{$e->lastname}}</option>
                                @endforeach
                              </select>
                            </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group">
                            <label>{{__('lang.branchname')}}</label>
                            <select class="form-control select2" name="branch_id" style="width: 100%;">
                              <option value="" selected>{{__('lang.select')}}</option>                      
                              @foreach($branch as $br)
                                  <option value="{{$br->id}}">{{$br->name}}</option>
                              @endforeach
                            </select>
                          </div>
                        </div>
                        <div class="col-md-12">
                          <div class="form-group">
                            <label>{{__('lang.rolename')}}</label>
                            <select class="form-control select2" name="role_id" style="width: 100%;">                     
                              @foreach($role as $rl)
                                  <option value="{{$rl->id}}">{{$rl->name}}</option>
                              @endforeach
                            </select>
                          </div>
                        </div>
                      </div>

                    </div>
                    <!-- /.col -->
                  </div>
                  <!-- /.row -->
                    
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">{{__('lang.save')}}</button>
                    <!--<a class="btn btn-warning" href="{{route('user.index')}}" >{{__('lang.back')}}</a>-->
                </div>
            </form>
            
          </div>

      </div>
    </div>
  </section>
@endsection

resources/views/backend/settings/user/index.blade.php
@extends('layouts.app.app')
@section('content')
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>{{__('lang.user')}}</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{route('dashboard.index')}}">{{__('lang.home')}}</a></li>
                <li class="breadcrumb-item active">{{__('lang.user')}}</li>
              </ol>
            </div>
          </div>
        </div>
      </section>
  
      <section class="content">
        <div class="container-fluid">
          <div class="row">
          @if(count($errors)>0)
              <div class="card-body">
                <div class="alert alert-danger alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <i class="icon fas fa-ban"> {{__('lang.error')}}</i></br>
                  @foreach($errors->all() as $error)
                  {{$error}} </br>
                  @endforeach
                </div>
              </div>
            @endif 
            <div class="col-12">
              <div class="card">
                <div class="card-header just">
                        <a href="{{route('user.create')}}" class="btn btn-primary btn-sm"><i class="fas fa-add"></i>{{__('lang.add')}}</a>
                        <a href="/user-excel" class="btn btn-success btn-sm"><i class="fas fa-add"></i>{{__('lang.add')}} Excel</a>
                </div>
                <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                      <th>{{__('lang.no')}}</th>
                      <th>{{__('lang.name')}}</th>
                      <th>{{__('lang.phone')}}</th>
                      <th>{{__('lang.email')}}</th>
                      <th>{{__('lang.name')}}</th>
                      <th>{{__('lang.percent')}}</th>
                      <th>{{__('lang.rolename')}}</th>
                      <th>{{__('lang.action')}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php
                      $stt = 1;    
                    @endphp

                    @foreach ($user as $u)
                    <tr>
                      <td style="text-align: center">{{$stt++}}</td>
                      <td>
                        {{$u->name}}
                        @if($u->divid_id =='' && $u->role_id ==10)
                        <p span class="badge badge-danger p-1">{{__('lang.no_divid')}}</p>
                        @endif
                      </td>
                      <td>{{$u->phone}}</td>
                      <td>{{$u->email}}</td>
                      <td>
                        @if($u->emp_id > 0)
                        {{$u->empname->firstname}} {{$u->empname->lastname}}
                        @endif
                      </td>
                      <td style="text-align: center">
                        @if($u->divid_id > 0)
                        {{$u->divid->name}} {{$u->divid->percent}} %
                        @endif
                      </td>
                      <td style="text-align: center">{{$u->rolename->name}}</td>
                      <td>
                        <form action=" {{ route('user.destroy', $u->id) }} " method="POST">
                          @csrf
                          @method('DELETE')

                          <a href="{{ route('user.edit', $u->id) }}" class="btn btn-warning btn-sm"><i class="fas fa-pencil-alt"></i></a>
                          <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('ທ່ານຕ້ອງການລຶບຂໍ້ມູນນີ້ ຫຼື ບໍ?')"><i class="fas fa-trash"></i></button>

                        </form>
                      </td>
                    </tr>
                    @endforeach
                    
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
@endsection