routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\LoginController;
use App\Http\Controllers\Backend\DepartController;
use App\Http\Controllers\Backend\MarriesController;
use App\Http\Controllers\Backend\VillageController;
use App\Http\Livewire\Backend\Divid\DividComponent;
use App\Http\Livewire\Backend\Order\OrderComponent;
use App\Http\Livewire\Backend\Order\PrintBillOrder;
use App\Http\Controllers\Backend\DistrictController;
use App\Http\Controllers\Backend\EmployeeController;
use App\Http\Controllers\Backend\PositionController;
//use App\Http\Controllers\Backend\Account\BranchController;
use App\Http\Controllers\Backend\ProvinceController;
use App\Http\Livewire\Backend\Order\DoSendComponent;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Livewire\Backend\Divid\AddDividComponent;
use App\Http\Livewire\Backend\Order\DoneSendComponent;
use App\Http\Livewire\Backend\Coupons\CouponsComponent;
use App\Http\Livewire\Backend\Divid\EditDividComponent;
use App\Http\Livewire\Backend\Employee\EmployeeContent;
use App\Http\Livewire\Backend\Order\EditOrderComponent;
use App\Http\Livewire\Backend\Order\OrderItemComponent;
use App\Http\Livewire\Backend\Customer\CustomerComponent;
use App\Http\Livewire\Backend\Order\CancelOrderComponent;
use App\Http\Controllers\Backend\Payroll\SalaryController;
use App\Http\Livewire\Backend\Coupons\AddCouponsComponent;
use App\Http\Livewire\Backend\Order\ConfirmOrderComponent;
//livewire
//by cheeyeeyang mouasue
use App\Http\Livewire\Backend\Order\SendingOrderComponent;
use App\Http\Controllers\Backend\Doc\StorageFileController;
use App\Http\Controllers\Backend\Ecommerce\SlideController;
use App\Http\Controllers\Backend\Payroll\PayrollController;
use App\Http\Livewire\Backend\Coupons\EditCouponsComponent;
use App\Http\Livewire\Backend\Order\DetailPaymentComponent;
use App\Http\Livewire\Backend\Order\EditOrderItemComponent;
use App\Http\Livewire\Backend\Payroll\PayrollBeforeContent;
use App\Http\Controllers\Backend\Account\CurrencyController;
use App\Http\Controllers\Backend\Doc\DocumentTypeController;
use App\Http\Controllers\Backend\Account\StatusAccController;
use App\Http\Controllers\Backend\Doc\ExternalPartsController;
use App\Http\Controllers\Backend\Doc\LocalDocumentController;
use App\Http\Controllers\Backend\Ecommerce\CatalogController;
use App\Http\Controllers\Backend\Ecommerce\ProductController;
use App\Http\Controllers\Backend\Ecommerce\ServiceController;
use App\Http\Livewire\Backend\Order\ShowCancelOrderComponent;
use App\Http\Controllers\Backend\Account\SettingAccController;
use App\Http\Controllers\Backend\Doc\ExportDocumentController;
use App\Http\Controllers\Backend\Doc\ImportDocumentController;
use App\Http\Controllers\Backend\Account\TransectionController;
use App\Http\Livewire\Backend\Order\UpdateOrderCancelComponent;

//end
/*
Route::get('/', function () {
return view('backend.login');
});*/

//App::setLocale($locale);
//Route::get('localization/{local}',[LocalController::class, 'index']);
Route::get('localization/{local}', function ($local) {
    Session::put('local', $local);
    return back();
});

//Frontend Website
Route::get('/', App\Http\Livewire\Frontend\HomeComponent::class)->name('home');
Route::get('/shop', App\Http\Livewire\Frontend\ShopComponent::class)->name('shop');
Route::get('/shop/product_detail/{id}', App\Http\Livewire\Frontend\ProductDetailComponent::class)->name('product_detail');
Route::get('/services', App\Http\Livewire\Frontend\ServiceComponent::class)->name('services');
Route::get('/services/service_detail/{id}', App\Http\Livewire\Frontend\ServiceDetailComponent::class)->name('service_detail');
Route::get('/customers', App\Http\Livewire\Frontend\CustomersComponent::class)->name('customers');
Route::get('/frontend/solutions', App\Http\Livewire\Frontend\SolutionsComponent::class)->name('solutions');
Route::get('/frontend/solutions/solution_detail/{id}', App\Http\Livewire\Frontend\SolutionsDetailComponent::class)->name('solution_detail');
Route::get('/about', App\Http\Livewire\Frontend\AboutComponent::class)->name('about');
Route::get('/contact', App\Http\Livewire\Frontend\ContactComponent::class)->name('contact');
Route::get('/cart', App\Http\Livewire\Frontend\CartComponent::class)->name('cart');
// Route::get('/checkout', App\Http\Livewire\Frontend\CheckoutComponent::class)->name('checkout');
Route::get('/wishlist', App\Http\Livewire\Frontend\WishlistComponent::class)->name('wishlist');
Route::get('/terms', App\Http\Livewire\Frontend\TermsComponent::class)->name('terms');
Route::get('/frontend/news', App\Http\Livewire\Frontend\NewsComponent::class)->name('news');
Route::get('/frontend/news/news_detail/{id}', App\Http\Livewire\Frontend\NewsDetailComponent::class)->name('news_detail');
//thankyou
Route::get('/thank-you', App\Http\Livewire\Frontend\ThankyouComponent::class)->name('thankyou');
Route::get('/privacy', function () {
    return file_get_contents(public_path() . '/privacy.html');
});

//Customers CustomerLoginComponent
Route::get('/customers/sign_in', App\Http\Livewire\Frontend\Auth\CustomerLoginComponent::class)->name('customer_sign_in');
Route::get('/customers/register', App\Http\Livewire\Frontend\Auth\CustomerRegisterComponent::class)->name('customer_register');

Route::resource('/loginadmincit', LoginController::class);

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});
Route::post('/saveToken', [LoginController::class, 'saveToken']);

// ============================  for admin ================= //
Route::group(['middleware' => 'adminLogin'], function () {
    //Customer
    Route::get('/customers/dashboard', App\Http\Livewire\Frontend\Customer\DashboardComponent::class)->name('customer.dashboard');
    Route::get('/customers/profile/{id}', App\Http\Livewire\Frontend\Auth\CustomerProfileComponent::class)->name('customer.profile');
    Route::get('/customers/shipping/{id}', App\Http\Livewire\Frontend\Auth\CustomerShippingComponent::class)->name('customer.shipping');
    Route::get('/customers/sign_out', [App\Http\Livewire\Frontend\Auth\CustomerLoginComponent::class, 'signOut'])->name('customer_sign_out');
    Route::get('/history', App\Http\Livewire\Frontend\Customer\CustomerHistoryComponent::class)->name('customer.history');
    Route::get('/view-history/{order_slug}/orderdetail', App\Http\Livewire\Frontend\Customer\ShowCustomerHistoryComponent::class)->name('customer.showhistory');
    Route::get('/order-divid', App\Http\Livewire\Frontend\Customer\OrderDivid::class)->name('customer.orderdivid');
    Route::get('/withraw-divid', App\Http\Livewire\Frontend\Customer\WithrawDividComponent::class)->name('customer.withrawdivid');
    Route::get('/withraw-success', App\Http\Livewire\Frontend\Customer\WithrawSuccessComponent::class)->name('customer.withdrawsuccess');
    Route::get('/liked-product', App\Http\Livewire\Frontend\Customer\LikedProductComponent::class)->name('customer.likedproduct');
    Route::get('/daily-customer-order-cart', App\Http\Livewire\Frontend\Customer\DailyCustomerCartComponent::class)->name('customer.dailycart');
    Route::get('/history-withraw-balance', App\Http\Livewire\Frontend\Customer\HistoryWithrawaComponent::class)->name('customer.historywithraw');
    Route::get('/daily-customer-shop', App\Http\Livewire\Frontend\Customer\DailyCustomerShopComponent::class)->name('customer.dailycustomershop');
    Route::get('/checkout', App\Http\Livewire\Frontend\CheckoutComponent::class)->name('checkout');
    //Backend
    Route::get('/module', [App\Http\Controllers\Backend\ModuleController::class, 'index'])->name('module.index');
    Route::resource('/dashboard', DashboardController::class);
    Route::resource('/depart', DepartController::class);
    Route::resource('/province', ProvinceController::class);
    Route::resource('/district', DistrictController::class);
    Route::resource('/village', VillageController::class);
    Route::resource('/marries', MarriesController::class);
    Route::resource('/position', PositionController::class);
    Route::resource('/user', UserController::class);

    Route::post('/user-excel', [App\Http\Controllers\Backend\ExcelUserController::class, 'store']);
    Route::get('/user-excel', [App\Http\Controllers\Backend\ExcelUserController::class, 'index']);
    Route::get('/user/changepass/{id}', [UserController::class, 'changepass'])->name('user.changepass');
    Route::PATCH('/user/updatepass/{id}', [UserController::class, 'updatepass'])->name('user.updatepass');
    Route::resource('/role', RoleController::class);
    Route::resource('/branch', App\Http\Controllers\Backend\BranchController::class);
    Route::resource('/misstype', App\Http\Controllers\Backend\MissTypeController::class);

    Route::resource('/transection', TransectionController::class);
    Route::PATCH('/approved/{id}', [TransectionController::class, 'approved'])->name('transection.approved');
    Route::PATCH('/rejected/{id}', [TransectionController::class, 'rejected'])->name('transection.rejected');
    //Route::resource('/branch',BranchController::class);
    Route::resource('/statusacc', StatusAccController::class);
    Route::resource('/currency', CurrencyController::class);
    Route::resource('/settingacc', SettingAccController::class);

    Route::resource('/import_doc', ImportDocumentController::class);
    Route::get('/import_doc/download/{id}', [ImportDocumentController::class, 'download'])->name('download_import');
    Route::resource('/export_doc', ExportDocumentController::class);
    Route::get('/export_doc/download/{id}', [ExportDocumentController::class, 'download'])->name('download_export');
    Route::resource('/local_doc', LocalDocumentController::class);

resources/views/backend/document/export/create.blade.php
@extends('layouts.app.app')
@section('content')
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>{{__('lang.export_doc')}}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('dashboard.index')}}">{{__('lang.home')}}</a></li>
            <li class="breadcrumb-item active">{{__('lang.export_doc')}}</li>
          </ol>
        </div>
      </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="col-lg-12">
          <div class="card card-default">

            <div class="card-header">
              <h3 class="card-title"><h4 class="card-title">{{__('lang.add')}}</h4></h3>
  
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>

            @if(count($errors)>0)
              <div class="card-body">
                <div class="alert alert-danger alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <i class="icon fas fa-ban"> {{__('lang.error')}}</i></br>
                  @foreach($errors->all() as $error)
                  {{$error}} </br>
                  @endforeach
                </div>
              </div>
            @endif 
            
            
            <form method="POST" action="{{route('export_doc.store')}}" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                  
                  <div class="row">
                    <div class="col-md-12">

                      <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                              <label for="doc_no">{{__('lang.doc_no')}}</label>
                              <input type="text" class="form-control" name="doc_no" placeholder="{{__('lang.doc_no')}}">
                            </div>
                          </div>
                        <div class="col-md-4">
                          <div class="form-group">
                            <label for="date">{{__('lang.date')}}</label>
                            <input type="date" class="form-control" name="date" placeholder="{{__('lang.date')}}">
                          </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                              <label>{{__('lang.doc_typename')}}</label>
                              <select class="form-control select2" name="doc_type" style="width: 100%;">                    
                                @foreach($doc_type as $type)
                                    <option value="{{$type->id}}">{{$type->name}}</option>
                                @endforeach
                              </select>
                            </div>
                          </div>
                      </div>

                      <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="short_title">{{__('lang.short_title')}}</label>
                                <input type="text" class="form-control" name="short_title" placeholder="{{__('lang.short_title')}}">
                            </div>
                        </div>
                      </div>

                      <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{{__('lang.external_partsname')}}</label>
                                <select class="form-control select2" name="external_parts_id" style="width: 100%;">                    
                                  @foreach($external_parts as $external)
                                      <option value="{{$external->id}}">{{$external->name}}</option>
                                  @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{{__('lang.storage_filename')}}</label>
                                <select class="form-control select2" name="storage_file_id" style="width: 100%;">                    
                                  @foreach($storage as $store)
                                      <option value="{{$store->id}}">{{$store->name}}</option>
                                  @endforeach
                                </select>
                            </div>
                        </div>
                      </div>

                      <div class="row">
                        <div class="col-md-12">
                          <div class="form-group">
                            <label for="file">{{__('lang.file')}}</label>
                            <input type="file" class="form-control" name="file" id="file">
                          </div>
                        </div>
                      </div>

                    </div>
                    <!-- /.col -->
                  </div>
                  <!-- /.row -->
                    
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">{{__('lang.save')}}</button>
                    <a class="btn btn-warning" href="{{route('export_doc.index')}}" >{{__('lang.back')}}</a>
                </div>
            </form>
            
          </div>

      </div>
    </div>
  </section>
@endsection

resources/views/backend/document/export/edit.blade.php
@extends('layouts.app.app')
@section('content')
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>{{__('lang.export_doc')}}</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('dashboard.index')}}">{{__('lang.home')}}</a></li>
            <li class="breadcrumb-item active">{{__('lang.export_doc')}}</li>
          </ol>
        </div>
      </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="col-lg-12">
          <div class="card card-default">

            <div class="card-header">
              <h3 class="card-title"><h4 class="card-title">{{__('lang.edit')}}</h4></h3>
  
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>

            @if(count($errors)>0)
              <div class="card-body">
                <div class="alert alert-danger alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <i class="icon fas fa-ban"> {{__('lang.error')}}</i></br>
                  @foreach($errors->all() as $error)
                  {{$error}} </br>
                  @endforeach
                </div>
              </div>
            @endif 
            
            
            <form method="POST" action="{{route('export_doc.update', $export_doc->id)}}" enctype="multipart/form-data">
                @csrf
                @method('PATCH')

                <div class="card-body">
                  
                  <div class="row">
                    <div class="col-md-12">

                      <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                              <label for="doc_no">{{__('lang.doc_no')}}</label>
                              <input type="text" class="form-control" name="doc_no" value="{{$export_doc->doc_no}}" placeholder="{{__('lang.doc_no')}}">
                            </div>
                          </div>
                        <div class="col-md-4">
                          <div class="form-group">
                            <label for="date">{{__('lang.date')}}</label>
                            <input type="date" class="form-control" name="date" value="{{$export_doc->date}}" placeholder="{{__('lang.date')}}">
                          </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                              <label>{{__('lang.doc_typename')}}</label>
                              <select class="form-control select2" name="doc_type" style="width: 100%;">                    
                                @foreach($doc_type as $type)
                                    <option 
                                        @if($export_doc->doc_type == $type->id)
                                            {{'selected'}}
                                        @endif
                                        value="{{$type->id}}">{{$type->name}}
                                    </option>
                                @endforeach
                              </select>
                            </div>
                          </div>
                      </div>

                      <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="short_title">{{__('lang.short_title')}}</label>
                                <input type="text" class="form-control" name="short_title" value="{{$export_doc->short_title}}" placeholder="{{__('lang.short_title')}}">
                            </div>
                        </div>
                      </div>

                      <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{{__('lang.external_partsname')}}</label>
                                <select class="form-control select2" name="external_parts_id" style="width: 100%;">                    
                                  @foreach($external_parts as $external)
                                    <option 
                                        @if($export_doc->external_parts_id == $external->id)
                                            {{'selected'}}
                                        @endif
                                        value="{{$external->id}}">{{$external->name}}
                                    </option>
                                  @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>{{__('lang.storage_filename')}}</label>
                                <select class="form-control select2" name="storage_file_id" style="width: 100%;">                    
                                  @foreach($storage as $store)
                                    <option 
                                        @if($export_doc->storage_file_id == $store->id)
                                            {{'selected'}}
                                        @endif
                                        value="{{$store->id}}">{{$store->name}}
                                    </option>
                                  @endforeach
                                </select>
                            </div>
                        </div>
                      </div>

                      <div class="row">
                        <div class="col-md-12">
                          <div class="form-group">
                            <label for="file">{{__('lang.file')}}</label>
                            <input type="file" class="form-control" name="file" id="file">
                          </div>
                        </div>
                      </div>

                    </div>
                    <!-- /.col -->
                  </div>
                  <!-- /.row -->
                    
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">{{__('lang.save')}}</button>
                    <a class="btn btn-warning" href="{{route('export_doc.index')}}" >{{__('lang.back')}}</a>
                </div>
            </form>
            
          </div>

      </div>
    </div>
  </section>
@endsection

resources/views/backend/document/export/index.blade.php
@extends('layouts.app.app')
@section('content')
    <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>{{__('lang.export_doc')}}</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{route('dashboard.index')}}">{{__('lang.home')}}</a></li>
                <li class="breadcrumb-item active">{{__('lang.export_doc')}}</li>
              </ol>
            </div>
          </div>
        </div>
      </section>
  
      <section class="content">
        <div class="container-fluid">
          <div class="row">

            <div class="col-12">
              <div class="card">
                <div class="card-header">
                  <a href="{{route('export_doc.create')}}" class="btn btn-primary btn-sm"><i class="fas fa-add"></i>{{__('lang.add')}}</a>
                </div>
                <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                    <tr style="text-align: center">
                      <th>{{__('lang.no')}}</th>
                      <th>{{__('lang.doc_no')}}</th>
                      <th>{{__('lang.date')}}</th>
                      <th>{{__('lang.doc_typename')}}</th>
                      <th>{{__('lang.short_title')}}</th>
                      <th>{{__('lang.external_partsname')}}</th>
                      <th>{{__('lang.creator')}}</th>
                      <th>{{__('lang.action')}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php
                      $stt = 1;    
                    @endphp

                    @foreach ($export_doc as $ex)
                    <tr>
                      <td width=5% style="text-align: center">{{$stt++}}</td>
                      <td style="text-align: center">
                          <a href="{{ route('export_doc.show', $ex->id) }}">{{$ex->doc_no}}</a>
                      </td>
                      <td>{{date('d/m/Y', strtotime($ex->date)) }}</td>
                      <td>{{$ex->doc_typename->name}}</td>
                      <td>{{$ex->short_title}}</td>
                      <td>{{$ex->external_parts_name->name}}</td>
                      <td>{{$ex->username->name}}</td>
                      <td style="text-align: center">
                        <form action=" {{ route('export_doc.destroy', $ex->id) }} " method="POST">
                          @csrf
                          @method('DELETE')

                          <a href="{{ route('export_doc.edit', $ex->id) }}" class="btn btn-warning btn-sm"><i class="fas fa-pencil-alt"></i></a>
                          <a href="{{route('download_export', $ex->id)}}" target="_blank" class="btn btn-success btn-sm"><i class="fas fa-eye"></i></a>
                          <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('ທ່ານຕ້ອງການລຶບຂໍ້ມູນນີ້ ຫຼື ບໍ?')"><i class="fas fa-trash"></i></button>

                        </form>
                      </td>
                    </tr>
                    @endforeach
                    
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
@endsection

resources/views/backend/document/export/show.blade.php
@extends('layouts.app.app')
@section('content')
        <section class="content">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-12">
                  <div class="card card-primary">
                    <div class="card-header">
                      <h3 class="card-title">{{__('lang.doc_typename')}}</h3>
                    </div>
                    <div class="card-body">
                      <strong><i class="fas fa-location-arrow mr-1"></i> {{__('lang.doc_no')}} - {{__('lang.date')}}</strong>
                      <p class="text-muted">
                        {{$export_doc->doc_no}} - {{date('d/m/Y', strtotime($export_doc->date)) }}
                      </p>
      
                      <hr>
      
                      <strong><i class="fas fa-map-marker-alt mr-1"></i> {{__('lang.doc_typename')}}</strong>
                      <p class="text-muted">{{$export_doc->doc_typename->name}}</p>
      
                      <hr>
      
                      <strong><i class="fas fa-clock mr-1"></i>{{__('lang.short_title')}}</strong>
                      <p class="text-muted"> {{$export_doc->short_title}} </p>
      
                      <hr>
      
                      <strong><i class="far fa-file-alt mr-1"></i> {{__('lang.external_partsname')}} - {{__('lang.storage_filename')}}</strong>
                      <p class="text-muted"> {{$export_doc->external_parts_name->name}} - {{$export_doc->storage_file_name->name}}</p>

                      <hr>
      
                      <strong><i class="fas fa-book mr-1"></i>{{__('lang.username')}} - {{__('lang.branchname')}}</strong>
                      <p class="text-muted"> {{$export_doc->username->name}} - {{$export_doc->branchname->name}} </p>

                      <hr>

                      <strong><i class="fas fa-book mr-1"></i>{{__('lang.file')}}</strong>
                      <p><a href="{{route('download_export', $export_doc->id)}}" target="_blank" class="btn btn-success">{{__('lang.download')}}</a> <a class="btn btn-warning" href="{{route('export_doc.index')}}" >{{__('lang.back')}}</a></p>

                    </div>
                  </div>
                </div>

              </div>
            </div>
          </section>
@endsection